"""
Production build script for VISION-AI-BACKEND
Run from project root: python build.py
"""

import os
import sys
import pkgutil
import importlib
import subprocess
import shutil

# ─────────────────────────────────────────────
# CONFIG — edit these if your structure changes
# ─────────────────────────────────────────────
ENTRY_SCRIPT   = "run.py"               # FastAPI uvicorn entry point
EXE_NAME       = "backend"              # output .exe name
APP_PACKAGE    = "app"                  # root Python package folder

# Folders whose contents should be bundled as data (non-Python assets)
DATA_FOLDERS = [
    "app/ml/models",
    "app/ml/config.yaml",
    "storage",
    "alembic",
    "SLCD-CODES",
]
# Extra pip packages that PyInstaller commonly misses
ALWAYS_HIDDEN = [
    # ── SQLAlchemy (full set) ──────────────────────────
    "sqlalchemy",
    "sqlalchemy.orm",
    "sqlalchemy.orm.decl_api",
    "sqlalchemy.ext.declarative",
    "sqlalchemy.dialects",
    "sqlalchemy.dialects.sqlite",
    "sqlalchemy.dialects.sqlite.pysqlite",
    "sqlalchemy.sql",
    "sqlalchemy.sql.default_comparator",
    "sqlalchemy.engine",
    "sqlalchemy.engine.reflection",
    "sqlalchemy.pool",
    "sqlalchemy.event",
    "sqlalchemy.events",

    # ── Uvicorn ───────────────────────────────────────
    "uvicorn",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",

    # ── FastAPI / Starlette ───────────────────────────
    "fastapi",
    "starlette",
    "starlette.routing",
    "starlette.middleware",
    "starlette.middleware.cors",
    "starlette.staticfiles",
    "starlette.responses",

    # ── Pydantic ──────────────────────────────────────
    "pydantic",
    "pydantic.v1",
    "pydantic_core",
    "pydantic.deprecated",

    # ── Alembic ───────────────────────────────────────
    "alembic",
    "alembic.runtime",
    "alembic.runtime.migration",
    "alembic.operations",

    # ── Auth / Security ───────────────────────────────
    "passlib",
    "passlib.handlers",
    "passlib.handlers.bcrypt",
    "jose",
    "jose.jwt",
    "jose.exceptions",

    # ── Other common ─────────────────────────────────
    "aiofiles",
    "multipart",
    "email_validator",
    "PIL",
    "cv2",
    "numpy",
    "duck_analyzer",
]


def discover_packages(root_package: str) -> list[str]:
    """Walk root_package and collect every sub-package as hidden import."""
    packages = [root_package]
    root_path = os.path.join(os.getcwd(), root_package)

    if not os.path.isdir(root_path):
        print(f"[WARN] Package folder '{root_package}' not found, skipping auto-discovery.")
        return packages

    for importer, modname, ispkg in pkgutil.walk_packages(
        path=[root_path],
        prefix=root_package + ".",
        onerror=lambda x: None,
    ):
        packages.append(modname)

    return packages


def build_datas(data_items: list[str]) -> list[tuple[str, str]]:
    """Return (src, dest) tuples for existing data items."""
    datas = []
    for item in data_items:
        if os.path.exists(item):
            if os.path.isfile(item):
                dest = os.path.dirname(item)
                datas.append((item, dest))
                print(f"[DATA] Including file: {item} -> {dest}/")
            else:
                datas.append((item, item))
                print(f"[DATA] Including folder: {item}/")
        else:
            print(f"[SKIP] Not found, skipping: {item}")
    return datas


def write_spec(
    entry: str,
    exe_name: str,
    hidden_imports: list[str],
    datas: list[tuple[str, str]],
) -> str:
    spec_path = f"{exe_name}.spec"

    # Format datas as Python list literal
    datas_repr = ",\n        ".join(
        f"({repr(src)}, {repr(dst)})" for src, dst in datas
    )

    # Format hidden imports
    hi_repr = ",\n    ".join(repr(h) for h in sorted(set(hidden_imports)))

    spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py — do not edit manually, re-run build.py instead

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['{entry}'],
    pathex=[str(Path.cwd()), str(Path.cwd() / 'app')],
    binaries=[],
    datas=[
        {datas_repr}
    ],
    hiddenimports=[
    {hi_repr}
    ],
    hookspath=['hooks'], 
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'PyQt5', 'PyQt6', 'wx'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='{exe_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,       # set False to hide the terminal window in production
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""
    with open(spec_path, "w") as f:
        f.write(spec_content)

    print(f"[SPEC] Written: {spec_path}")
    return spec_path


def clean_previous():
    for folder in ["build", "dist"]:
        if os.path.exists(folder):
            shutil.rmtree(folder)
            print(f"[CLEAN] Removed old {folder}/")


def main():
    print("\n=== Vision-AI Backend — Production Build ===\n")

    if not os.path.exists(ENTRY_SCRIPT):
        print(f"[ERROR] Entry script not found: {ENTRY_SCRIPT}")
        sys.exit(1)

    # 1. Auto-discover all sub-packages
    print(f"[SCAN] Discovering packages under '{APP_PACKAGE}/'...")
    app_packages = discover_packages(APP_PACKAGE)
    print(f"[SCAN] Found {len(app_packages)} packages/modules")

    # 2. Combine with always-hidden imports
    all_hidden = app_packages + ALWAYS_HIDDEN

    # 3. Collect data folders
    datas = build_datas(DATA_FOLDERS)

    # 4. Clean old build artifacts
    clean_previous()

    # 5. Write .spec file
    spec_path = write_spec(ENTRY_SCRIPT, EXE_NAME, all_hidden, datas)

    # 6. Run PyInstaller
    print(f"\n[BUILD] Running PyInstaller...\n")
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--clean", spec_path],
        check=False,
    )

    if result.returncode == 0:
        exe_path = os.path.join("dist", f"{EXE_NAME}.exe")
        size_mb = os.path.getsize(exe_path) / (1024 * 1024) if os.path.exists(exe_path) else 0
        print(f"\n[SUCCESS] Build successful!")
        print(f"   Output : dist/{EXE_NAME}.exe")
        print(f"   Size   : {size_mb:.1f} MB")
        print(f"\nTest it: .\\dist\\{EXE_NAME}.exe")
    else:
        print(f"\n❌ Build failed with exit code {result.returncode}")
        print("   Check the output above for missing modules and add them to ALWAYS_HIDDEN in build.py")
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
